# Build stage

FROM node:18-alpine as build-stage

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

ENV NODE_ENV=production

RUN yarn build

# Production stage
FROM node:18-alpine as production-stage

WORKDIR /app

COPY --from=BUILD_IMAGE /app/package*.json yarn.lock ./
COPY --from=BUILD_IMAGE /app/.next ./.next
COPY --from=BUILD_IMAGE /app/public ./public
COPY --from=BUILD_IMAGE /app/node_modules ./node_modules

ENV NODE_ENV=production